name: Deploy InformationsWerkstatt

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---- Azure Login via Secret (Service Principal JSON) ----
      - name: Azure login (service principal via creds JSON)
        uses: azure/login@v2
        with:
          auth-type: service-principal
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ---- (Optional) Infrastruktur deployen, wenn Bicep vorhanden ----
      - name: Deploy Infrastructure (Bicep)
        if: hashFiles('infra/main.bicep') != ''
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg_informationswerkstatt
          template: infra/main.bicep
          parameters: >
            env=dev
            sqlAdminPassword=${{ secrets.SQL_ADMIN_PASSWORD }}

      # ---- (Optional) Node nur vorbereiten, wenn Frontend da ist ----
      - name: Setup Node.js
        if: hashFiles('frontend/package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ---- (Optional) Frontend bauen ----
      - name: Build Frontend
        if: hashFiles('frontend/package.json') != ''
        working-directory: frontend
        run: |
          npm ci
          npm run build

      # ---- (Optional) Frontend deployen, nur wenn SWA-Token existiert ----
      - name: Deploy Frontend (Static Web Apps)
        if: hashFiles('frontend/package.json') != '' && secrets.AZURE_SWA_TOKEN != ''
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"
          output_location: "dist"

      # ---- Platzhalter: API / Functions später ----
      - name: API placeholder
        run: echo "API-Deployment folgt, sobald Code vorhanden ist."
      - name: Functions placeholder
        run: echo "Functions-Deployment folgt, sobald Code vorhanden ist."
