name: smoke-azure-login
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (client secret)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Show Azure context
        run: az account show --query '{name:name, id:id, tenantId:tenantId}' -o table

      - name: Verify RG access
        run: az group show --name rg_informationswerkstatt --query '{name:name, location:location, id:id}'
